var express = require('express');
var router = express.Router();

const title_list = [
  {'id': 'ID', 'Term': 'Term', 'Description': 'Description', 'References': 'References'}
];

const stuff = [
  {'id': 1, 'Term': 'Development Team', 'Description': 'Are responsible for creating software programs consisting of designing, creation and testing. This team focuses on writing the code, implementing new features and well as ensuring the quality of service (QoS) of the product', 'References': 'What is a development team? (2023) Coursera. Available at: https://www.coursera.org/articles/what-is-development-team (Accessed: July 20, 2023).'},
  {'id': 2, 'Term': 'Operations Team', 'Description': 'Also known as SysOps. This team covers a wide range of tasks including IT operations and administration. These tasks include monitoring and managing system performance, managing system backups and recovery as well as ensuring security and compliance ', 'References': 'DevOps vs SysOps: Key differences (no date) Knowledgehut.com. Available at: https://www.knowledgehut.com/blog/devops/devops-vs-sysops (Accessed: July 20, 2023).'},
  {'id': 3, 'Term': 'Quality Assurance Team (QA)', 'Description': 'Develops and maintains standards for the product development ', 'References': 'Naidu, S. (2022) “All you need to know about Quality assurance team structure,” QA Touch, 12 July. Available at: https://www.qatouch.com/blog/all-you-need-to-know-about-quality-assurance-team-structure/ (Accessed: July 20, 2023).'},
  {'id': 4, 'Term': 'Product Managers', 'Description': 'Is responsible for the entire product development lifecycle ', 'References': 'DeClute, D. (2022) Product owner vs. product manager: What’s the difference?, Theserverside.com. Available at: https://www.theserverside.com/tip/Product-owner-vs-product-manager-Whats-the-difference?_gl=1*1ja3s8s*_ga*MTk1NzY5OTA4Mi4xNjc4NzY2ODA0*_ga_TQKE4GS5P9*MTY5MDEzMDEzOS4yNC4xLjE2OTAxMzAyNTIuMC4wLjA.&_ga=2.55787689.384197809.1690130148-1957699082.1678766804 (Accessed: July 20, 2023).'},
  {'id': 5, 'Term': 'Security Teams', 'Description': 'These teams are responsible for protecting IT infrastructure, edge devices, networks and data.  They are responsible for preventing data breaches and monitoring and reacting to attacks', 'References': 'Understanding SOC team roles and responsibilities (no date) Chronicle. Available at: https://chronicle.security/blog/posts/understanding-the-soc-team-roles-and-responsibilities/ (Accessed: July 23, 2023).'},
  {'id': 6, 'Term': 'Customers and Users', 'Description': 'The end users benefit from the end product. As well as provide user feedback', 'References': 'Bird, J. (2019) How to improve users lives when users & customers are not the same people, Medium. Available at: https://jeremybird276.medium.com/user-vs-customer-its-not-mutually-exclusive-b7f954c80b1d (Accessed: July 23, 2023).'},
  {'id': 7, 'Term': 'DevOps Engineers', 'Description': 'Mainly act as facilitators. This team is in charge of bridging the development and operations team by breaking down the barriers', 'References': 'Bigelow, S. J. (2019) DevOps engineer, IT Operations. TechTarget. Available at: https://www.techtarget.com/searchitoperations/definition/DevOps-engineer (Accessed: July 23, 2023).'},
  {'id': 8, 'Term': 'Sequential Methodology', 'Description': 'It is also called a linear sequential model, classic life cycle or waterfall model. It suggests a systematic, sequential approach to Software Development that begins at a systematic level and progresses through communication, planning, modeling, construction, and deployment', 'References': 'The linear sequential model of software development (2019) WADIC. Available at: https://wadic.net/software-development-linear-sequential-model/ (Accessed: July 23, 2023).'},
  {'id': 9, 'Term': 'Agile Methodology', 'Description': 'Agile methodology is a project management approach that involves breaking the project into phases and emphasizes continuous collaboration and improvement', 'References': 'Hoory, L. (2022) What is Waterfall methodology? Here’s how it can help your project management strategy, Forbes. Available at: https://www.forbes.com/advisor/business/what-is-waterfall-methodology/ (Accessed: July 23, 2023).  '},
  {'id': 10, 'Term': 'Waterfall Methodology', 'Description': 'The Waterfall approach was established in 1970 by Winston w. Royce. It contains five phases of management, where each requires a deliverable from the previous phase to proceed. Waterfall is ideal for projects like software development, where the end result is clearly established before starting, and is best suited for projects that require a lot of predictability.', 'References': 'Hoory, L. (2022) What is Waterfall methodology? Here’s how it can help your project management strategy, Forbes. Available at: https://www.forbes.com/advisor/business/what-is-waterfall-methodology/ (Accessed: July 23, 2023).  '},
  {'id': 11, 'Term': 'Enterprise DevOps', 'Description': 'Enterprise DevOps is a set of practices and priciples that assist an organization when developing software. These set of practices allow the development team to develop the software faster and more efficiently.', 'References': 'Jaitly, R. (2022) “Enterprise DevOps solutions - how DevOps works for enterprise?,” SoluteLabs, 10 November. Available at: https://www.solutelabs.com/blog/enterprise-devops (Accessed: August 20, 2023).'},
  {'id': 12, 'Term': 'DevOps Automation', 'Description': 'Is a set of tools and technologies that perform tasks routinely. These tasks would normally be done manually by engineers.', 'References': 'Gunja, S. (2022) What is DevOps automation?, Dynatrace. Available at: https://www.dynatrace.com/news/blog/what-is-devops-automation/ (Accessed: August 20, 2023).'},
  {'id': 13, 'Term': 'DevOps Cycle', 'Description': 'DevOps Cycle is a continuous software development process. This process includes multiple stages such as Plan, Build, Integrate, Deploy, Monitor, Operate and Feedback. These steps will be taking place throughouth the lifecycle of the software.', 'References': 'Das, S. (2023) DevOps Lifecycle : Different phases in DevOps, BrowserStack. Available at: https://www.browserstack.com/guide/devops-lifecycle (Accessed: August 20, 2023).'},
  {'id': 14, 'Term': 'The 7Cs of DevOps', 'Description': 'The different phases of DevOps lifecycle can be broken down into the 7Cs. Continuous Development, Continuous Integration, Continuous Testing, Continuous Deployment, Continuous Feedback, Continuous Monitoring and Continuous Operations.', 'References': 'Das, S. (2023) DevOps Lifecycle : Different phases in DevOps, BrowserStack. Available at: https://www.browserstack.com/guide/devops-lifecycle (Accessed: August 20, 2023).'},
  {'id': 15, 'Term': 'DevOps principles', 'Description': 'In DevOps various teams are involved in the development and deployment of a software. These teams  adhere to a set of principals that help them in delivering software at a faster and of a higher quality that organizations that follow various other methods.', 'References': 'Atlassian (no date) DevOps principles, Atlassian. Available at: https://www.atlassian.com/devops/what-is-devops (Accessed: August 20, 2023).'},
  {'id': 16, 'Term': 'Continuous Integration', 'Description': 'Is the process of automating the integration of the code into the project. Developers would merge everything into a central repository. Building the code as well as testing the code can be done via the repository.', 'References': 'Atlassian (no date a) DevOps, Atlassian. Available at: https://www.atlassian.com/devops (Accessed: August 20, 2023).'},
  {'id': 17, 'Term': 'Continuous Testing', 'Description': 'In this phase the code is tested for errors and bugs. The usability of the software is thoroughly tested in this phase.', 'References': 'What is DevOps lifecycle? Definition, key components, and management best practices (no date) Spiceworks. Available at: https://www.spiceworks.com/tech/devops/articles/what-is-devops-lifecycle/ (Accessed: August 20, 2023).'},
  {'id': 18, 'Term': 'Continuous Deployment', 'Description': 'This phase ensures smooth hassle free deployment of the product.', 'References': 'What is DevOps lifecycle? Definition, key components, and management best practices (no date) Spiceworks. Available at: https://www.spiceworks.com/tech/devops/articles/what-is-devops-lifecycle/ (Accessed: August 20, 2023).'},
  {'id': 19, 'Term': 'Continuous Monitoring', 'Description': 'This phase determines the efficiency of the product by constantly monitoring its performance.', 'References': 'What is DevOps lifecycle? Definition, key components, and management best practices (no date) Spiceworks. Available at: https://www.spiceworks.com/tech/devops/articles/what-is-devops-lifecycle/ (Accessed: August 20, 2023).'},
  {'id': 20, 'Term': 'Continuous Operations', 'Description': 'The final phase, this phase ensures automated releases for the product. It also allows the development team to detect issues as well as implement fixes and roll-out updated versions of the product as well.', 'References': 'What is DevOps lifecycle? Definition, key components, and management best practices (no date) Spiceworks. Available at: https://www.spiceworks.com/tech/devops/articles/what-is-devops-lifecycle/ (Accessed: August 20, 2023).'},
  {'id': 21, 'Term': 'Container', 'Description': 'A container is a standard unit of software that packages up code and all its dependencies so the application runs quickly and reliably from 1 computing environoment to another', 'References': 'What is a container? (no date) Docker. Available at: https://www.docker.com/resources/what-container/ (Accessed: September 11, 2023).'},
  {'id': 22, 'Term': 'Microservices', 'Description': 'Microservices is an architectural style that structures an application as a collection of services that are independently deployable, loosely coupled. This allows organizations to deliver large, complex applications rapidly and reliably.', 'References': 'Richardson, C. (2018) Microservices Patterns: With examples in Java. New York, NY: Manning Publications.'},
  {'id': 23, 'Term': 'Docker', 'Description': 'A Docker container is a packaging format that packages all the code and dependencies of an application in a standard format that allows it to run reliably and quickly accross multiple computing environments.', 'References': 'What is Docker? (no date) Oracle.com. Available at: https://www.oracle.com/au/cloud/cloud-native/container-registry/what-is-docker/ (Accessed: September 11, 2023).'},
  {'id': 24, 'Term': 'Infrastructure as Code (IaC)', 'Description': 'IaC is the managing and provisioning of infrastructure through code instead of through manual processes', 'References': 'What is Infrastructure as Code (IaC)? (no date) Redhat.com. Available at: https://www.redhat.com/en/topics/automation/what-is-infrastructure-as-code-iac (Accessed: September 11, 2023).'},
  {'id': 25, 'Term': 'Docker compose', 'Description': 'Compose is a took for defining and running multi-container Docker applications. With the use of a YAML file application services can be configured.', 'References': 'Docker Compose overview (2023) Docker Documentation. Available at: https://docs.docker.com/compose/ (Accessed: September 11, 2023).'},
  {'id': 26, 'Term': 'Volumes', 'Description': 'Volumes are the preferred mechanism for persisting data generated by and used by Docker containers', 'References': 'Volumes (2023) Docker Documentation. Available at: https://docs.docker.com/storage/volumes/ (Accessed: September 11, 2023).'},
  {'id': 27, 'Term': 'Container Networking', 'Description': 'Container networking refers to the ability for containers to connect to and communicate with each other or to non Docker workloads', 'References': 'Networking overview (2023) Docker Documentation. Available at: https://docs.docker.com/network/ (Accessed: September 11, 2023).'},
  {'id': 28, 'Term': 'Bridge Network', 'Description': 'In terms of Docker, a bridge network uses a software brdige which allows containers connected to the same bridge network to communicate while providing isolation from containers which are not connected to that bridge network', 'References': 'Bridge network driver (2023) Docker Documentation. Available at: https://docs.docker.com/network/drivers/bridge/ (Accessed: September 11, 2023).'},
  {'id': 29, 'Term': 'Overlay Network', 'Description': 'The Overlay netwokr driver creates a distributed network among multiple Docker daemon hosts. This network sits on top the host specific networks which allows containers connected to it to communicate securely when encryption is enabled.', 'References': 'Overlay network driver (2023) Docker Documentation. Available at: https://docs.docker.com/network/drivers/overlay/ (Accessed: September 11, 2023).'},
  {'id': 30, 'Term': 'Macvlan Network', 'Description': 'Macvlan networks directly connect the applications that monitor network traffic to the physical network. This network assigns a MAC address to each containers virtual network interface making it appear to be a physical network interface directly connected to the physical network.', 'References': 'Macvlan network driver (2023) Docker Documentation. Available at: https://docs.docker.com/network/drivers/macvlan/ (Accessed: September 11, 2023).'},


]


/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'SIT722 DevOps Glossary',
   subheading: 'Welcome to my website showing a collection of DevOps terms and their brief descriptions',
  titles: title_list, list: stuff });
});

module.exports = router;
